general.import = [
  "~/.config/alacritty/colors/gruvbox_dark.toml",
]

general.live_config_reload = true

########################################
# Environment
########################################
[env]
TERM      = "xterm-256color"
COLORTERM = "truecolor"

########################################
# Window
########################################
[window]
opacity         = 0.95
decorations     = "Full"
startup_mode    = "Windowed"
dynamic_padding = true
padding         = { x = 10, y = 10 }
title           = "Alacritty"
class           = { instance = "alacritty", general = "Alacritty" }
dynamic_title   = true

########################################
# Scrolling
########################################
[scrolling]
history    = 100000
multiplier = 3

########################################
# Font
########################################
[font]
size                = 13.5
builtin_box_drawing = true

[font.normal]       # Hack Nerd Font chain
family = "Hack Nerd Font"
style  = "Regular"

[font.bold]
family = "Hack Nerd Font"
style  = "Bold"

[font.italic]
family = "Hack Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style  = "Bold Italic"


[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

########################################
# Cursor
########################################
[cursor]
blink_interval   = 500
unfocused_hollow = true
thickness        = 0.15

[cursor.style]
shape    = "Block"
blinking = "On"

########################################
# Selection & Mouse
########################################
[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

########################################
# Terminal-wide options
########################################
[terminal]
shell = { program = "/bin/zsh", args = ["--login", "-i"] }
osc52 = "CopyPaste"

########################################
# Visual Bell
########################################
[bell]
animation = "EaseOutExpo"
duration  = 150
color     = "#fb4934"
command   = "None"

########################################
# Hints (URL opener)
########################################
[hints]
alphabet = "asdfghjkl"

[[hints.enabled]]
regex           = "(https?://[\\w\\-./?%&=+#~:]+)"
command         = { program = "~/.config/alacritty/bin/url-run", args = ["{hint}"] }
post_processing = true
hyperlinks      = true
persist         = false
mouse           = { enabled = true, mods = "None" }
binding         = { key = "U", mods = "Control|Shift" }

########################################
# Keyboard Bindings
########################################
[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Q", mods = "Control|Shift", action = "Quit" },

  { key = "F11", mods = "None",          action = "ToggleFullscreen" },
  { key = "M",   mods = "Control|Shift", action = "ToggleMaximized" },

  { key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",  mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "Key0",   mods = "Control|Shift", action = "ResetFontSize" },

  { key = "V", mods = "Control|Alt",   action = "ToggleViMode" },
  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "Y", mods = "Control|Shift", action = "CopySelection" },
  { key = "L", mods = "Control|Shift", action = "ClearHistory" },

  { key = "T", mods = "Control|Shift", command = { program = "~/.config/alacritty/bin/alacritty-tmux-new-window" } },
  { key = "Space", mods = "Control|Shift", chars = "\u0002" },

  { key = "O", mods = "Control|Shift", command = { program = "~/.config/alacritty/bin/alacritty-toggle-opacity" } },
  { key = "D", mods = "Control|Shift", command = { program = "bash", args = ["-lc", "pwd | tr -d '\\n' | xclip -selection clipboard"] } },
]

########################################
# Debugging (disable for normal use)
########################################
[debug]
log_level          = "Warn"
print_events       = false
persistent_logging = false
